

# AGENT PARAMETERS
PLAYER_RADIUS = 3.0
PLAYER_SPEED  = 2.0

# REWARD PARAMETERS
JAIL_REWARD = -50
JAIL_TIME_REWARD = -2
TAGGING_REWARD = 50
FLAG_REWARD_WEIGHT = 10
TAKE_FLAG_REWARD = 100
CAPTURE_FLAG_REWARD = 500